### ISSUE TITLE
EPIC: Deephaven Dependencies

### ISSUE THREAD

**Issue by bmingles** [deephaven/vscode-deephaven#11]
There are a number of things that will need to be done to improve code re-usability and remove certain responsibilities from the extension altogether. There is work to be done outside of the extension repo to support this:

- [ ] https://github.com/deephaven/deephaven-core/issues/5537
- [ ] DH-16725: @deephaven-enterprise/jsapi-types - this will need to be thought through more holistically of how we want to handle Enterprise support. Will want to make DHE code more re-usable for this
- [ ] [DH-17425: web-client-ui monorepo](https://deephaven.atlassian.net/browse/DH-17425)
   - [ ] Worker creation / management UI
   - [ ] WebClientData utils
   - [ ] ClientUtils
