### ISSUE TITLE
EPIC: vscode-deephaven for Enterprise

### ISSUE THREAD

**Issue by bmingles** [deephaven/vscode-deephaven#17]
The current `vscode-deephaven` extension only works with Deephaven Community. We also need to support Enterprise.

- [ ] Determine how we want to package this (separate extension, does repo need to be private, etc.)
- [ ] Enterprise npm packages: https://github.com/deephaven/vscode-deephaven/issues/11
- [ ] Worker management UI
