### ISSUE TITLE
Design: Workspace Experience

### ISSUE THREAD

**Issue by bmingles** [deephaven/vscode-deephaven#72]
There's a number of things that need to be done to improve the general workspace experience for vscode users. A couple of them have been called out already in #7 and #10. This epic is intended to capture specific design items + subtasks for this. We'll need to consider both the DHC + DHE setups.

- [ ] [DHC: Worker lifecycle management #7](https://github.com/deephaven/vscode-deephaven/issues/7)
- [ ] [DHE: Worker Lifecycle Management #76](https://github.com/deephaven/vscode-deephaven/issues/76)
- [ ] [DHC: Workspace dependencies #104](https://github.com/deephaven/vscode-deephaven/issues/104)
- [ ] [DHE: Workspace dependencies #105](https://github.com/deephaven/vscode-deephaven/issues/105)
- [ ] ~DHE Virtual filesystem? - might be nice to support this, but the local GIT experience is more optimal in most cases, so may not be worth it.~ Not going to pursue this at this point.

**Comment by bmingles** [comment]
Don, Bender, and I had a design discussion today. I broke out action tasks accordingly. Closing this as the high level design brainstorming is done.
